################################################################################
# robot configs
################################################################################
sim_robot_variables:
  urdf_filename: "/models/kinova_7dof/urdf/kinova_7dof.urdf"
  mesh_foldername: "/models/kinova_7dof/meshes"
  use_fixed_base: True

  base_name: "Actuator1"
  joint_names: [
    "Actuator1", "Actuator2", "Actuator3", "Actuator4", "Actuator5", "Actuator6", "Actuator7" 
  ]  # pinocchio order
  limb_names: ["arm"]
  limb_endeff_names: ["EndEffector_Link"]
  limb_endeff_joint_names: ["EndEffector"]
  limb_endeff_frame_names: [ "EndEffector"]

  base_init_pos: [0., 0., 0., 0., 0., 0., 1.] # posture
  base_init_vel: [0., 0., 0., 0., 0., 0.]
  joint_init_pos: [0., 0., 0., 0., 0., 0., 0.]
  joint_init_vel: [0., 0., 0., 0., 0., 0., 0.]


################################################################################
# control configs
################################################################################
control_variables:
  joint_names: [
    "Actuator1", "Actuator2", "Actuator3", "Actuator4", "Actuator5", "Actuator6", "Actuator7"
  ]  # pinocchio order
  joint_des_pos: [0., 0.1, 0., 0.5, 0., -0.5, 0.]
